---
- name: Set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - rc.local
    - sysctl

- name: apply iptables rules for MAAS gateway
  shell: |
    iptables -A FORWARD -o "{{ maas_network_interfaces['public'].name }}" -i "{{ maas_network_interfaces['private'].name }}" -s      "{{ maas_network_interfaces['private'].address }}" -m conntrack --ctstate NEW -j ACCEPT
    iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -t nat -F POSTROUTING
    iptables -t nat -A POSTROUTING -o "{{ maas_network_interfaces['public'].name }}" -j MASQUERADE
  changed_when: false
  tags:
    - iptables
  
- name: ensure rc.local file is executable
  file:
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0755
  tags:
    - rc-local

- name: ensure iptable rules are loaded automatically
  blockinfile:
    dest: /etc/rc.local
    owner: root
    mode: 0755
    insertbefore: 'exit 0'
    marker: "# {mark} Added by maas role"
    state: present
    block: "{{ lookup('template', 'iptables_rules_block.j2') }}"
  tags:
    - rc.local


