---
#TODO: configure this through a template instead
- name: set maas listening IP in regiond.conf
  replace:
    dest: /etc/maas/regiond.conf
    regexp: '^maas_url\:\s+.*'
    replace: "maas_url: http://{{ maas_listening_ip }}:5240/MAAS"
    owner: "{{ maas_system_user_name }}"
    group: root
    backup: yes
  tags:
    - maas-regiond
  notify:
    - Restart maas-regiond

#TODO: configure this through a template instead
- name: set maas listening IP in rackd.conf
  replace:
    dest: /etc/maas/rackd.conf
    regexp: '^maas_url\:\s+.*'
    replace: "maas_url: http://{{ maas_listening_ip }}:5240/MAAS"
    owner: "{{ maas_system_user_name }}"
    group: root
    backup: yes
  tags:
    - maas-rackd
  notify:
    - Restart maas-rackd

- name: create maas admin user
  shell: maas createadmin --username="{{ maas_user_ui }}" --email=hamzaachi01@gmail.com --password="{{ maas_password_ui }}"
  register: maas_admin
  failed_when: false
  changed_when: false
  tags:
    - maas-admin

- name: get maas API key
  command: maas-region apikey --username="{{ maas_user_ui }}"
  register: maas_apikey
  changed_when: false
  tags:
    - maas-api-key

- name: generate ssh key
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: "/root/.ssh/id_rsa"
  register: gen_ssh_key
  run_once: true
  tags:
    - gen-ssh-key

- set_fact:
    ssh_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  when: gen_ssh_key.rc == 0

- name: check existing ssh key
  shell: "maas {{ maas_user_ui }} sshkeys read|jq '.[].key'"
  register: is_sshkey_exists
  changed_when: false
  run_once: true
  tags:
    - check-ssh-key

- name: set maas ssh key
  shell: "{{ maas_login_cmd }} {{ maas_apikey.stdout }};maas {{ maas_user_ui }} sshkeys create key='{{ ssh_key }}'"
  changed_when: false
  run_once: true
  when: is_sshkey_exists.stdout.find("{{ ansible_hostname }}") == -1
  tags:
    - create-ssh-key

- name: configure maas global settings
  shell: "{{ maas_login_cmd }} {{ maas_apikey.stdout }};maas {{ maas_user_ui }} maas set-config  name={{ item.name }} value={{ item.value }}"
  with_items: "{{ maas_settings }}"
  changed_when: false
  tags:
    - maas-settings
  
